version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      FLOORPLAN_STORAGE_DIR: /data/storage
      FLOORPLAN_CELERY_BROKER_URL: redis://redis:6379/0
      FLOORPLAN_CELERY_RESULT_BACKEND: redis://redis:6379/0
      FLOORPLAN_CELERY_TASK_ALWAYS_EAGER: "false"
      FLOORPLAN_CONVERTER_PATH: ${FLOORPLAN_CONVERTER_PATH:-/opt/oda/ODAFileConverter.exe}
    volumes:
      - ../../storage:/data/storage
      - ../../originFile:/opt/oda:ro
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    working_dir: /app
    command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      FLOORPLAN_STORAGE_DIR: /data/storage
      FLOORPLAN_CELERY_BROKER_URL: redis://redis:6379/0
      FLOORPLAN_CELERY_RESULT_BACKEND: redis://redis:6379/0
      FLOORPLAN_CELERY_TASK_ALWAYS_EAGER: "false"
      FLOORPLAN_CONVERTER_PATH: ${FLOORPLAN_CONVERTER_PATH:-/opt/oda/ODAFileConverter.exe}
    volumes:
      - ../../storage:/data/storage
      - ../../originFile:/opt/oda:ro
    depends_on:
      - redis

  frontend:
    image: node:22-alpine
    working_dir: /workspace
    command: >-
      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000/api}
    volumes:
      - ../../frontend:/workspace
    ports:
      - "5173:5173"
    depends_on:
      - api
    profiles: ["dev"]
